server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gtfs
    username: postgres #gtfs
    password: postgres #gtfs
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false


#app:
#  python:
#    base-url: http://localhost:8000