server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gtfs
    username: postgres #gtfs
    password: postgres #gtfs
    #временно для тестирования только с редисом
#    hikari:
#      initializationFailTimeout: 0
#      minimum-idle: 0
#      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: none
    # временно для тестирования только с редисом
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

vehpos:
  recency-seconds: 600
  keys:
    trip-prefix: "vehpos:SL:"
